DROP TABLE IF EXISTS `ACTION`;

CREATE TABLE `ACTION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `RESPONSE` longtext NOT NULL,
  `ACTION` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_etrgskeg931buj2g6lg0xeyym` (`ACTION`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `REQUEST`;

CREATE TABLE `REQUEST` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `REQUEST_BODY` longtext,
  `REMOTE_HOST` varchar(30) DEFAULT NULL,
  `EXTRACTED_CONTENT` varchar(100) DEFAULT NULL,
  `DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `METHOD` varchar(9) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1; 
